name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install poetry
      uses: abatilo/actions-poetry@v2.3.0
      with:
        poetry-version: '1.5.0'
    - name: Install pip dependencies
      run: poetry install
    - name: Package
      run: |
        poetry version ${{ github.event.release.tag_name }}
        poetry build
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.pypi_token }}
